#Coverage for gitlab with jacoco

image: maven:3-jdk-11

stages:
  - test build

general test:
  stage: test build
  script:
    - mvn verify
    - cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
  only:
    - master